euv_spectra_app/main/routes.py
import json
import plotly
import os
import zipfile
import io
import itertools
from flask import Blueprint, request, render_template, redirect, url_for, session, flash, current_app, jsonify, send_file, send_from_directory
from flask_mail import Message
from datetime import timedelta
from euv_spectra_app.extensions import *
from euv_spectra_app.main.forms import ManualForm, StarNameForm, PositionForm, ModalForm, ContactForm
from euv_spectra_app.models import StellarObject, PegasusGrid
from euv_spectra_app.helpers import insert_data_into_form, to_json, from_json, create_plotly_graph, remove_objs_from_obj_dict
main = Blueprint("main", __name__)

@main.context_processor
def inject_form():
    return dict(contact_form=ContactForm())


@main.before_request
def make_session_permanent():
    """Initialize session."""
    session.permanent = True
    app.permanent_session_lifetime = timedelta(minutes=60)
    if not session.get('modal_show'):
        session['modal_show'] = False


@main.route('/', methods=['GET', 'POST'])
def homepage():
    """Home and submit route for search bar forms."""
    if request.args.get('form') == 'extended':
        extend_form = True
    else:
        extend_form = False
    session['modal_show'] = False
    stellar_object = StellarObject()
    manual_form = ManualForm()
    name_form = StarNameForm()
    position_form = PositionForm()
    modal_form = ModalForm()

    if request.method == 'POST':
        if position_form.validate_on_submit():
            # Home position form
            print('position form validated!')
            stellar_object.position = position_form.coords.data
            stellar_object.get_stellar_parameters()
        elif name_form.validate_on_submit():
            # Home name form
            print(f'name form validated!')
            stellar_object.star_name = name_form.star_name.data
            stellar_object.get_stellar_parameters()

        if hasattr(stellar_object, 'modal_page_error_msg'):
            # check if there were any errors returned from searching databases
            return redirect(url_for('main.error', msg=stellar_object.modal_page_error_msg))
        for msg in stellar_object.modal_error_msgs:
            flash(msg, 'warning')
        insert_data_into_form(stellar_object, modal_form)

        # store the object as a json variable for persistence
        session['stellar_object'] = json.dumps(to_json(stellar_object))
        session['modal_show'] = True
        return render_template('home.html', manual_form=manual_form, name_form=name_form, position_form=position_form, modal_form=modal_form, stellar_obj=stellar_object)

    flash('Website is under development. Files are not available for use yet. For testing purposes, try out object GJ 338 B.', 'warning')
    return render_template('home.html', manual_form=manual_form, name_form=name_form, position_form=position_form, extend_form=extend_form)


@main.route('/modal-submit', methods=['GET', 'POST'])
def submit_modal_form():
    """Submit route for modal form."""
    manual_form = ManualForm()
    name_form = StarNameForm()
    position_form = PositionForm()
    modal_form = ModalForm()

    # Retrieve the JSON formatted string from the session
    target_json = session.get('stellar_object')
    # Deserialize the JSON formatted string back into an object
    stellar_object = from_json(target_json)
    # Populate the modal form with data from object
    insert_data_into_form(stellar_object, modal_form)
    modal_form.populate_obj(request.form)

    fluxes = ['fuv', 'nuv', 'fuv_err', 'nuv_err']

    if request.method == 'POST':
        if modal_form.validate_on_submit():
            for field in modal_form:
                # ignoring all manual parameters, submit, csrf token, and catalog names
                if 'manual' in field.name and field.data is not None:
                    # if a manual parameter is submitted, add that data to the object
                    unmanual_field = field.name.replace('manual_', '')
                    if getattr(modal_form, unmanual_field).data == 'Manual':
                        # Only add the data from manual form if the unmanual field has a value of 
                        # 'Manual' (meaning manual radio option was checked)
                        if unmanual_field in fluxes:
                            if 'err' in field.name and float(field.data) == 0:
                                # If a flux error was inputted as 0, put as None
                                setattr(stellar_object.fluxes, unmanual_field, None)
                            else:
                                setattr(stellar_object.fluxes, unmanual_field, float(field.data))
                        else:
                            setattr(stellar_object, unmanual_field, float(field.data))
            session['stellar_object'] = json.dumps(to_json(stellar_object))
            return redirect(url_for('main.return_results'))
    return render_template('home.html', manual_form=manual_form, name_form=name_form, position_form=position_form, modal_form=modal_form, stellar_obj=stellar_object)


@main.route('/manual-submit', methods=['POST'])
def submit_manual_form():
    """Submit route for manual form."""
    form = ManualForm(request.form)
    stellar_object = StellarObject()
    fields_not_to_include = ['dist_unit', 'fuv_flag',
                             'nuv_flag', 'fuv_unit', 'nuv_unit', 'submit', 'csrf_token']
    flux_data = ['fuv', 'fuv_err', 'nuv', 'nuv_err']

    # iterate over each field in the form and set the attributes to the stellar object
    if form.validate_on_submit():
        # STEP 1a: If both flags are null, return flashed error message (with form extended)
        for fieldname, value in form.data.items():
            if fieldname in fields_not_to_include:
                # Deal with the fields not to include
                # (mostly unit checking and conversions and flag functionalities)
                if fieldname == 'dist_unit' and value == 'mas':
                    # CHECK DISTANCE UNIT
                    # if the distance unit is milliarcseconds (mas) convert to parsecs
                    stellar_object.dist = int(1 / (form.dist.data / 1000))
                elif (fieldname == 'fuv_unit' and value == 'mag' and form.fuv.data is not None) or (fieldname == 'nuv_unit' and value == 'mag' and form.nuv.data is not None):
                    # Converting FUV/NUV magnitudes to fluxes
                    # Check which flux & err
                    flux = fieldname[:3]
                    flux_err = f'{flux}_err'
                    flux_flag = f'{flux}_flag'
                    flux_value = float(getattr(form, flux).data)
                    flux_err_value = getattr(form, flux_err).data
                    # if galex unit is in magnitude (mag), convert to flux (in microjanskies)
                    print(f'CONVERTING {flux} WITH VAL {flux_value} FROM MAG TO FLUX')
                    flux_converted = stellar_object.fluxes.convert_mag_to_ujy(flux_value, str(flux))
                    # if there is an error, get the error as well (there is an error if it is not None or not 0)
                    if flux_err_value is not None and flux_err_value != '0':
                        upper_lim = flux_value + float(flux_err_value)
                        lower_lim = flux_value - float(flux_err_value)
                        print(f'Upper limit of {flux}: {upper_lim}. Lower limit of {flux}: {lower_lim}')
                        upper_lim_converted = stellar_object.fluxes.convert_mag_to_ujy(upper_lim, str(flux))
                        lower_lim_converted = stellar_object.fluxes.convert_mag_to_ujy(lower_lim, str(flux))
                        print(f'CONVERTED Upper limit of {flux}: {upper_lim_converted}. Lower limit of {flux}: {lower_lim_converted}')
                        up_err = upper_lim_converted - flux_converted
                        low_err = flux_converted - lower_lim_converted
                        print(f'NEW UPPER VAL: {up_err}, NEW LOW VAL: {low_err}')
                        err_converted = (up_err + low_err) / 2
                        print(f'SETTING THE CONVERTED FLUX ERR {flux_err} TO {err_converted}')
                        setattr(stellar_object.fluxes, flux_err, err_converted)
                    # Reassign form value so if checked again in flag check, will assign to converted val
                    getattr(form, flux).data = flux_converted
                    # Check if the flux has any flags and set flux of stellar object fluxes to converted val accordingly
                    if getattr(form, flux_flag).data is not None:
                        flag = getattr(form, flux_flag).data
                        # if it does, assign the converted flux to that 
                        if flag == 'saturated':
                            # assign to saturated value
                            flux_saturated = f'{flux}_saturated'
                            print(f'SETTING THE CONVERTED SATURATED FLUX {flux_saturated} TO {flux_converted}')
                            setattr(stellar_object.fluxes, flux_saturated, flux_converted)
                        elif flag == 'upper_limit':
                            # assign to upper limit value
                            flux_upper_limit = f'{flux}_upper_limit'
                            print(f'SETTING THE CONVERTED UPPER LIMIT FLUX {flux_upper_limit} TO {flux_converted}')
                            setattr(stellar_object.fluxes, flux_upper_limit, flux_converted)
                    else:
                        print(f'SETTING THE CONVERTED FLUX {flux} TO {flux_converted}')
                        # else, assign converted flux to normal fuv attribute
                        setattr(stellar_object.fluxes, flux, flux_converted)
                elif 'flag' in fieldname:
                    flux = fieldname[:3]
                    flux_err = f'{flux}_err'
                    if value == 'null':

euv_spectra_app/templates/about.html
{% extends 'base.html' %}
{% set active_page = "about" %}

{% block title %}About{% endblock %}
{% block content %}
    <div id="about-hero">
        <img src="{{ url_for('static', filename='imgs/solar-img-banner.png') }}" alt="" class="full-width img img-fluid" id="about-hero-img">
        <h1 class="text-center" style="padding-top: 80px;">About</h1>
    </div>

    <nav class="nav nav-tabs justify-content-center mt-5">
        <a class="nav-link active" aria-current="page" href="#nav-overview">Overview</a>
        <a class="nav-link" href="#nav-data-products">Data Products</a>
        <a class="nav-link" href="#nav-data-access">Data Access</a>
    </nav>


    <div id="nav-overview">
        <h3 class="mt-5 pt-4 text-center">Overview</h3>
        <p class="text-center">———</p>
        <p>The PEGASUS webtool identifies a generalized high resolution (Δλ < 0.01 Å) synthetic extreme ultraviolet (EUV; 100-1000 Å) spectrum for a searched target exoplanet host star (M or K spectral type) from a grid of ~1,500 PHOENIX spectra with T<sub>eff</sub> = 2500 - 5044 K, log(g) = 4.45 - 5.32 cm/s<sup>2</sup>, and M = 0.08 - 0.89 M<sub>sun</sub>. <br> <br>

            Required inputs for returning a spectrum are T<sub>eff</sub>, log(g), mass, radius, distance, and GALEX FUV and NUV flux densities. <br> <br>
            
            T<sub>eff</sub>, log(g), and mass are used for two purposes:
            <ol>
                <li>To select a PHOENIX photosphere model that is used for subtracting out the star's photospheric contribution from the GALEX flux densities
                    The photosphere model grid is sampled as such: T<sub>eff</sub> = 2500 - 5100 K (ΔT<sub>eff</sub> = 10 K), log(g) = 4.35 - 5.35 cm/s<sup>2</sup> (Δlog(g) = 0.01), M = 0.08 - 0.9 M<sub>sun</sub> (ΔM = 0.1)) </li>
                <li>To select a <a href="/index-spectra">subgrid</a> of closest matching spectral subtype from which to identify the best representative model for the searched star</li>
            </ol><br>
            
            Radius and distance are used to scale the GALEX fluxes to the stellar surface. The PHOENIX models are similarly scaled to the stellar surface and have no photospheric contribution included. <br> <br>
            
            GALEX FUV and NUV flux densities are used to identify the best representative model of the star. A χ<sup>2</sup> minimization is done to identify the model with the closest matching (photospheric-flux-corrected) FUV and NUV fluxes to the target star. <br> <br>
            
            The downloadable data product from the main search function is a PHOENIX spectrum (EUV - IR; 100 Å to 100 μm) in FITS file format. The wavelengths (given in Å) are in vacuum and the wavelength grid has a resolution of &lt;0.1 Å. Please note that the wavelength grid is not uniformly spaced. The flux densities (given in ergs/cm<sup>2</sup>/s/Å) are that at the stellar surface and are scalable to a distance D via (R_star/D)<sup>2</sup>.<br><br>
            <b>NOTE</b>: The data product is a <b>general representation of the star, tailored to predict the EUV wavelengths.</b> Wavelengths longer than 1000 Å may not match observed spectra of the star due to the model having slightly a different temperature, gravity, and/or mass from the searched target star.
        </p><br>
        <h5 class="py-3">Notes if utilizing our built-in search function</h5>
        <p>
            The PEGASUS webtool queries the <a href="https://exoplanetarchive.ipac.caltech.edu/">NExSci</a> catalog for T<sub>eff</sub>, log(g), mass, radius, and distance. Please confirm that the values you select are correct for your target. Clicking on the NExSci hyperlink on the modal with returned values will navigate you to that star's NASA Exoplanet Archive Summary page, which may provide additional options for stellar parameters. <br><br>

            The PEGASUS webtool queries <a href="http://galex.stsci.edu/GR6/?page=mastform">GALEX catalog 6/7</a> for FUV and NUV flux densities. It queries the catalog by RA and dec, which have been corrected for proper motion via the values returned by the <a href="https://gea.esac.esa.int/archive/">GAIA EDR3 catalog</a>.<br><br>
        </p>
        <h5 class="py-3">Citation</h5>
        <p>If you make use of the synthetic spectra downloaded from the PEGASUS webtool, please cite Peacock et al. (2023).</p><br>
    </div>


    <div id="nav-data-products">
        <h3 class="mt-5 pt-4 text-center">Data Products</h3>
        <p class="text-center">———</p>
        <p class="ms-5">
            The data file naming convention is as follows: <br><br>
            PEGASUS.<b>&lt;SpT></b>.Teff=<b>&lt;Teff></b>.logg=<b>&lt;logg></b>.TRgrad=<b>&lt;TRgrad></b>.cmtop=<b>&lt;cmtop></b>.cmin=<b>&lt;cmin></b>.fits <br><br>
            
            Where <br>
            <b>&lt;SpT></b> = Spectral subtype of the model <br>
            <b>&lt;Teff></b> = Effective Temperature of the model in K <br>
            <b>&lt;logg></b> = Log of the surface gravity of the model in cm s<sup>2</sup><br>
            <b>&lt;TRgrad></b> = Log of the temperature gradient in the transition region in K dyne<sup>-1</sup> cm<sup>2</sup> <br>
            <b>&lt;cmtop></b> = Log of the column mass at the top of the chromosphere (absolute value) in g cm<sup>-2</sup> <br>
            <b>&lt;cmin></b> = Log of the column mass at the temperature minimum (absolute value) in g cm<sup>-2</sup> <br>
                
        </p> <br>
    </div>

    <div id="nav-data-access">
        <h3 class="mt-5 pt-4 text-center">Data Access</h3>
        <p class="text-center">———</p>
        <p class="ms-4"><i>Python Script to Run</i></p>
        <p class="ms-5"><code>from astropy.io import fits</code> <br>
            <code>import matplotlib.pyplot as plt</code> <br>
            <code>spec = fits.getdata('PEGASUS.M0.Teff=3850.logg=4.78.TRgrad=8.5.cmtop=6.5.cmin=3.5.fits',1)</code> <br>
            <code>plt.plot(spec['WAVELENGTH'],spec['FLUX'])</code> <br>
            <code>plt.suptitle('Synthetic EUV spectrum for &lt;STAR>')</code> <br>
            <code>plt.xlabel('Wavelength (Å)')</code> <br>
            <code>plt.ylabel('Flux Density (erg/cm2/s/Ang)')</code> <br>
            <code>plt.xrange(100,1000)</code> <br>
            <code>plt.show()</code> <br>
        </p>
        <br>
    </div>
{% endblock %}

euv_spectra_app/templates/acknowledgements.html
{% extends 'base.html' %}
{% set active_page = "acknowledgements" %}
{% block title %}Acknowledgements{% endblock %}
{% block content %}
    <div id="about-hero">
        <img src="{{ url_for('static', filename='imgs/solar-img-banner.png') }}" alt="" class="full-width img img-fluid" id="about-hero-img">
        <h1 class="text-center" style="padding-top: 80px;">Acknowledgements</h1>
    </div>
    <div class="row mt-5">
        <div class="col-lg-7 offset-lg-2">
            <p class="mt-3">
                We wish to thank and recognize the following for their contribution to this project <br> <br>
        
                <b>Affiliations:</b> <br>
                University of Maryland, Baltimore County <br>
                NASA Goddard Space Flight Center <br>
                University of Arizona, Lunar and Planetary Lab <br><br>
        
                <b>High Performance Computing Centers:</b> <br>
                NASA Center for Climate Simulation <br> 
                University of Arizona HPC <br>
                University of Arizona PACMAN  <br><br>
        
                <b>Archives:</b> <br>
                NASA Exoplanet Archive <br>
                MAST <br>
                GALEX <br><br>
        
            </p>
        </div>
    </div>
{% endblock %}

euv_spectra_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static', filename='styles/styles.css')}}">
    <link rel="icon" href="{{url_for('static', filename='imgs/icon.png')}}">
    <link rel="apple-touch-icon" href="{{url_for('static', filename='imgs/icon.png')}}">
    <!-- jQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <!-- Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <!-- FontAwesome Script -->
    <script src="https://kit.fontawesome.com/40fbc81c42.js" crossorigin="anonymous"></script>
    <!-- PlotLy -->
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.6/d3.min.js"></script>

    <title>{% block title %}{% endblock %}</title>

</head>
    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-BV7GFMDEKD"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'G-BV7GFMDEKD');
    </script>
    
    <body class="d-flex flex-column min-vh-100 large-top-padding">
        {% include 'partials/navbar.html' %}
        
        <div class="container">
            {% for category, message in get_flashed_messages(with_categories=true) %}
                {% if 'GALEX Error:' not in message and 'Error connecting to the NASA Exoplanet Archive' not in message and 'Error connecting to SIMBAD' not in message and 'Error connecting to MAST' not in message %}
                    <div class="alert alert-{{category}} mt-2" role="alert">
                        {{ message }}
                    </div>
                {% endif %}
            {% endfor %}

            {% block content %}{% endblock %}
            {% block contact_form %}
                {% include 'partials/contact_form.html' %}
            {% endblock %}
        </div>
        {% include 'partials/footer.html' %}
        {% block script %}{% endblock %}
    </body>
</html>

euv_spectra_app/templates/error.html
{% extends 'base.html' %}
{% set active_page = "none" %}
{% block title %}Error{% endblock %}
{% block content %}
    <div class="mt-5">
        <a href="/" class="me-auto">← Back to home</a>
    </div>
    <div class="text-center">
        <h1>Oops...</h1>
        <p>{{ error_msg }}</p>
        {% if manual_form_error_msg %}
            {% include 'partials/manual_form_error_msg.html' %}
        {% endif %}
    </div>
{% endblock %}

euv_spectra_app/templates/faqs.html
{% extends 'base.html' %}
{% set active_page = "faqs" %}
{% block title %}Frequently Asked Questions{% endblock %}
{% block content %}
    <div id="about-hero">
        <img src="{{ url_for('static', filename='imgs/solar-img-banner.png') }}" alt="" class="full-width img img-fluid" id="about-hero-img">
        <h1 class="text-center" style="padding-top: 80px;">Frequently Asked Questions (FAQ)</h1>
    </div>


    <div class="row my-5 pt-4 mx-4">
        <div class="accordion accordion-flush" id="accordionFlushExample">

            <div class="accordion-item">
                <h2 class="accordion-header" id="header-Q1">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#Q1" aria-expanded="false" aria-controls="Q1">
                        <b>Q1. </b> &nbsp; Can I search for non-exoplanet host stars?
                    </button>
                </h2>
                <div id="Q1" class="accordion-collapse collapse" aria-labelledby="header-Q1" data-bs-parent="#accordionFlushExample">
                    <div class="accordion-body">
                        Yes, but the required inputs (T<sub>eff</sub>, log(g), mass, radius, distance, and GALEX FUV and NUV flux densities) must be entered manually via <a href="{{ url_for('main.homepage', form='extended') }}">this form</a> on the home page. <br>
                        This is because we query the NExSci archive for these parameters, which only contains information regarding exoplanet host stars.
                    </div>
                </div>
            </div>
                
            <div class="accordion-item">
                <h2 class="accordion-header" id="header-Q2">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#Q2" aria-expanded="false" aria-controls="Q2">
                        <b>Q2. </b> &nbsp; Why are GALEX flux densities used to identify the representative PHOENIX EUV spectrum?
                    </button>
                </h2>
                <div id="Q2" class="accordion-collapse collapse" aria-labelledby="header-Q2" data-bs-parent="#accordionFlushExample">
                    <div class="accordion-body">
                        GALEX was an all sky survey that measured FUV and NUV photometry for stars of all ages and masses and therefore many M and K stars have this data available. 
                        Further, stellar FUV and NUV flux originates in the chromosphere and transition region, overlapping heavily with the formation temperatures of the EUV. <br><br>
                        The EUV forms in the transition region and corona, with most of the shorter EUV wavelengths (&lt;400 Å) originating from the hottest coronal layers and the bulk of the EUV wavelengths (400-912 Å) coming from the transition region. 
                        To constrain the full upper atmosphere with corona requires contemporaneous X-ray and UV measurements, and since that's not readily available for all exoplanet host stars, the models do not include coronae. <br><br>
                        That being said, the GALEX measurements are sufficient to constrain the temperature structure in the chromosphere and transition region (up to 200,000 K), and so we are able to confidently predict the majority of the EUV spectrum.
                    </div>
                </div>
            </div>

            <div class="accordion-item">
                <h2 class="accordion-header" id="header-Q3">
                    <button class="accordion-button {% if question_id != 'Q3' %}collapsed{% endif %}" type="button" data-bs-toggle="collapse" data-bs-target="#Q3" aria-expanded="{% if question_id == 'Q3' %}true{% else %}false{% endif %}" aria-controls="Q3">
                        <b>Q3. </b> &nbsp; What if my star doesn't have GALEX measurements, only has a GALEX detection in one band, or has a detection that is an upper/lower limit?
                    </button>
                </h2>
                <div id="Q3" class="accordion-collapse collapse {% if question_id == 'Q3' %}show{% endif %}" aria-labelledby="header-Q3" data-bs-parent="#accordionFlushExample">
                    <div class="accordion-body">
                        <i>If your star has no GALEX measurement:</i> A proxy can be identified from this table [INSERT TABLE] <br><br>
                        <i>If your star only has a GALEX detection in one band:</i> We will estimate the flux density in the missing band with the following relations:
                            <p>&nbsp; For Early M Stars: log<sub>10</sub>(FUV) = (1.14&plusmn;0.03) * log<sub>10</sub>(NUV) - (1.17&plusmn;0.09) <a href="https://ui.adsabs.harvard.edu/abs/2014AJ....148...64S/abstract">(Richey-Yowell et al. 2023)</a></p>
                            <p>&nbsp; For Late M Stars:  log<sub>10</sub>(FUV) = (0.96&plusmn;0.02) * log<sub>10</sub>(NUV) - (0.43&plusmn;0.04) <a href="https://ui.adsabs.harvard.edu/abs/2014AJ....148...64S/abstract">(Richey-Yowell et al. 2023)</a></p>
                        <i>If a detection is flagged as an upper or lower limit:</i> We will return all models that satisfy the condition, returning the model that most closely matches the limit as the “Best Match”
                    </div>
                </div>
            </div>

            <div class="accordion-item">
                <h2 class="accordion-header" id="header-Q4">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#Q4" aria-expanded="false" aria-controls="Q4">
                        <b>Q4. </b> &nbsp; What do I do if my star name is not recognized by the search function?
                    </button>
                </h2>
                <div id="Q4" class="accordion-collapse collapse" aria-labelledby="header-Q4" data-bs-parent="#accordionFlushExample">
                    <div class="accordion-body">
                        Try searching by ICRS coordinates OR enter the parameters manually through the drop-down link on the <a href="{{ url_for('main.homepage', form='extended') }}">Home</a> page.
                    </div>
                </div>
            </div>

            <div class="accordion-item">
                <h2 class="accordion-header" id="header-Q5">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#Q5" aria-expanded="false" aria-controls="Q5">
                        <b>Q5. </b> &nbsp; Why is the search taking so long (>5 minutes)?
                    </button>
                </h2>
                <div id="Q5" class="accordion-collapse collapse" aria-labelledby="header-Q5" data-bs-parent="#accordionFlushExample">
                    <div class="accordion-body">
                        Our search function queries multiple databases, and one of these resources may be down temporarily. You may enter the parameters manually or try again at a later time.
                    </div>
                </div>
            </div>

            <div class="accordion-item">
                <h2 class="accordion-header" id="header-Q6">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#Q6" aria-expanded="false" aria-controls="Q6">
                        <b>Q6. </b> &nbsp; What are the units of the downloaded data products?
                    </button>
                </h2>
                <div id="Q6" class="accordion-collapse collapse" aria-labelledby="header-Q6" data-bs-parent="#accordionFlushExample">
                    <div class="accordion-body">
                        Wavelengths are given in Angstroms and are in vacuum. Please note that the wavelength grid is not uniformly spaced. The flux densities are given in ergs/cm<sup>2</sup>/s/Å and are scaled to the stellar surface. 
                    </div>
                </div>
            </div>

            <div class="accordion-item">
                <h2 class="accordion-header" id="header-Q7">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#Q7" aria-expanded="false" aria-controls="Q7">
                        <b>Q7. </b> &nbsp; Why is the wavelength grid not uniformly spaced?
                    </button>
                </h2>
                <div id="Q7" class="accordion-collapse collapse" aria-labelledby="header-Q7" data-bs-parent="#accordionFlushExample">
                    <div class="accordion-body">
                        The models are computed with high wavelength sampling (Δλ = 0.01 Å) at wavelengths below 6000 Å and lower wavelength sampling above 6000 Å (Δλ ≥ 3 Å). Additional wavelength points are added to each non-LTE emission line.
                    </div>
                </div>
            </div>

            <div class="accordion-item">
                <h2 class="accordion-header" id="header-Q8">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#Q8" aria-expanded="false" aria-controls="Q8">
                        <b>Q8. </b> &nbsp; Why do the spectra look noisy?
                    </button>
                </h2>
                <div id="Q8" class="accordion-collapse collapse" aria-labelledby="header-Q8" data-bs-parent="#accordionFlushExample">
                    <div class="accordion-body">
                        There is no added noise to the models. The apparent noisiness is the result of thousands of emission lines that are included in our models.
                    </div>
                </div>
            </div>

        </div>
    </div>
{% endblock %}

euv_spectra_app/templates/load-api.html
{% extends 'base.html' %}
{% set active_page = "none" %}
{% block title %}API Test Route{% endblock %}
{% block content %}
    <p>API ROUTE LOADED</p>
    {% block contact_form %}{% endblock %}
{% endblock %}

euv_spectra_app/templates/load_api.html
{% extends 'base.html' %}
{% set active_page = "none" %}
{% block title %}API Test Route{% endblock %}
{% block content %}
    <p>API ROUTE LOADED</p>
    {% block contact_form %}{% endblock %}
{% endblock %}